# Generated by Django 4.0.2 on 2022-10-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Projects',
        ),
    ]
