# Generated by Django 4.0.2 on 2022-10-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApis', '0003_test_delete_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Projects',
        ),
    ]
